/*
 * E-Commerce APP (REST API)
 * A basic API for working with the Swagger Tools.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.33
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ECommerceAppRestApi);
  }
}(this, function(expect, ECommerceAppRestApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ECommerceAppRestApi.AccountsApi();
  });

  describe('(package)', function() {
    describe('AccountsApi', function() {
      describe('accountsDeleteOne', function() {
        it('should call accountsDeleteOne successfully', function(done) {
          // TODO: uncomment, update parameter values for accountsDeleteOne call
          /*

          instance.accountsDeleteOne(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('accountsGetAll', function() {
        it('should call accountsGetAll successfully', function(done) {
          // TODO: uncomment accountsGetAll call
          /*

          instance.accountsGetAll(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('accountsGetOne', function() {
        it('should call accountsGetOne successfully', function(done) {
          // TODO: uncomment, update parameter values for accountsGetOne call
          /*

          instance.accountsGetOne(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('accountsNew', function() {
        it('should call accountsNew successfully', function(done) {
          // TODO: uncomment accountsNew call
          /*

          instance.accountsNew(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('accountsUpdateOne', function() {
        it('should call accountsUpdateOne successfully', function(done) {
          // TODO: uncomment, update parameter values for accountsUpdateOne call
          /*

          instance.accountsUpdateOne(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
