/*
 * E-Commerce APP (REST API)
 * A basic API for working with the Swagger Tools.
 *
 * OpenAPI spec version: 1.0.0
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 3.0.33
 *
 * Do not edit the class manually.
 *
 */
(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ECommerceAppRestApi);
  }
}(this, function(expect, ECommerceAppRestApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ECommerceAppRestApi.CartApi();
  });

  describe('(package)', function() {
    describe('CartApi', function() {
      describe('cartCheckout', function() {
        it('should call cartCheckout successfully', function(done) {
          // TODO: uncomment cartCheckout call
          /*

          instance.cartCheckout(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('cartDeleteAll', function() {
        it('should call cartDeleteAll successfully', function(done) {
          // TODO: uncomment cartDeleteAll call
          /*

          instance.cartDeleteAll(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('cartDeleteOne', function() {
        it('should call cartDeleteOne successfully', function(done) {
          // TODO: uncomment, update parameter values for cartDeleteOne call
          /*

          instance.cartDeleteOne(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('cartGetAll', function() {
        it('should call cartGetAll successfully', function(done) {
          // TODO: uncomment cartGetAll call
          /*

          instance.cartGetAll(function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('cartGetOne', function() {
        it('should call cartGetOne successfully', function(done) {
          // TODO: uncomment, update parameter values for cartGetOne call
          /*

          instance.cartGetOne(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
      describe('cartUpdateOne', function() {
        it('should call cartUpdateOne successfully', function(done) {
          // TODO: uncomment, update parameter values for cartUpdateOne call
          /*

          instance.cartUpdateOne(id, function(error, data, response) {
            if (error) {
              done(error);
              return;
            }

            done();
          });
          */
          // TODO: uncomment and complete method invocation above, then delete this line and the next:
          done();
        });
      });
    });
  });

}));
